### PR TITLE
Fixing all linting, setting $SERVER vars in config

### PR DESCRIPTION
**Pull request by karllhughes**
Addresses https://github.com/betterweekdays/glassdoor/issues/15

This introduces several breaking changes as I had to change variable names in order to get the Drupal linter to pass. I think it would be a good idea to do a major version tag release after you merge this in.

Happy Friday!

### CODE REVIEW

**Comment by karllhughes** [comment]
@indytechcook just wanted to check in with you and see if you've had time to review this or if you had any questions. Happy to help clarify if need be!

**Comment by karllhughes** [comment]
@indytechcook just checking in on this again. Wanting to implement it on my site, but was hoping to get these changes merged in first :smile:

**Comment by karllhughes** [comment]
@indytechcook it's been a while, so just hoping to get feedback on this PR if you can. If not, I'm just going to spin up a new composer package for now. Thanks!

**Comment by karllhughes** [comment]
Thanks Neil!

**Comment by indytechcook** [comment]
I created a new Tag also for this 1.2.1.

**Pull request merged**
